### ISSUE TITLE
Missing import at "Combining objects into a program"

### ISSUE THREAD

**Issue by nicoguaro** [veekaybee/textedit#1]
The following snippet is missing ``import sys``

```
>>> import os
>>> os.getcwd() #where we're currently running code
'/python_packaging'

>>> print('\n'.join(sys.path)) # all the paths Python checks for packages
```

**Comment by veekaybee** [comment]
Thanks for opening this. Could you link to the piece of code/comment? I'm having trouble finding it again.

**Comment by nicoguaro** [comment]
I think it's in line 776 of this file

    https://github.com/veekaybee/veekaybee.github.io/blob/master/_posts/2017-09-26-python-packaging.md

**Comment by veekaybee** [comment]
Aha, fixed thanks!
